# @package _global_

defaults:
  - _self_

paths:
  data_dir: "../data/${dataset.name}"
  results_dir: "../temp_files/results_${dataset.name}"
  tensorboard_dir: "../temp_files/logs_${dataset.name}"
  checkpoints_dir: "../temp_files/checkpoints_${dataset.name}"

dataset:
  name: "vk-lsvd"

train:
  rqvae_train_parts: [0, 8]
  rqvae_eval_parts: [9, 10]

inference:
  allowed_items_parts: [0, 8]

model:
  input_dim: 64
  hidden_dim: 64
  codebook_size: 512
  num_codebooks: 3
  beta: 0.25

training:
  seed_value: 42
  device: "cuda:0"
  num_epochs: 100
  batch_size: 4096
  lr: 1e-4
